# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/dill/Downloads/desktop-goose/Desktop Goose v0.31/DesktopGoosev0.31"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/dill/Downloads/desktop-goose/Desktop Goose v0.31/DesktopGoosev0.31"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/dill/Downloads/desktop-goose/Desktop Goose v0.31/DesktopGoosev0.31/CMakeFiles" "/home/dill/Downloads/desktop-goose/Desktop Goose v0.31/DesktopGoosev0.31//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/dill/Downloads/desktop-goose/Desktop Goose v0.31/DesktopGoosev0.31/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P "/home/dill/Downloads/desktop-goose/Desktop Goose v0.31/DesktopGoosev0.31/CMakeFiles/VerifyGlobs.cmake"
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CppGoose

# Build rule for target.
CppGoose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CppGoose
.PHONY : CppGoose

# fast build rule for target.
CppGoose/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/build
.PHONY : CppGoose/fast

#=============================================================================
# Target rules for targets named gemini_client_test

# Build rule for target.
gemini_client_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemini_client_test
.PHONY : gemini_client_test

# fast build rule for target.
gemini_client_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemini_client_test.dir/build.make CMakeFiles/gemini_client_test.dir/build
.PHONY : gemini_client_test/fast

#=============================================================================
# Target rules for targets named ggml-base

# Build rule for target.
ggml-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base
.PHONY : ggml-base

# fast build rule for target.
ggml-base/fast:
	$(MAKE) $(MAKESILENT) -f third_party/whisper.cpp/ggml/src/CMakeFiles/ggml-base.dir/build.make third_party/whisper.cpp/ggml/src/CMakeFiles/ggml-base.dir/build
.PHONY : ggml-base/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f third_party/whisper.cpp/ggml/src/CMakeFiles/ggml.dir/build.make third_party/whisper.cpp/ggml/src/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml-cpu

# Build rule for target.
ggml-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu
.PHONY : ggml-cpu

# fast build rule for target.
ggml-cpu/fast:
	$(MAKE) $(MAKESILENT) -f third_party/whisper.cpp/ggml/src/CMakeFiles/ggml-cpu.dir/build.make third_party/whisper.cpp/ggml/src/CMakeFiles/ggml-cpu.dir/build
.PHONY : ggml-cpu/fast

#=============================================================================
# Target rules for targets named whisper

# Build rule for target.
whisper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper
.PHONY : whisper

# fast build rule for target.
whisper/fast:
	$(MAKE) $(MAKESILENT) -f third_party/whisper.cpp/src/CMakeFiles/whisper.dir/build.make third_party/whisper.cpp/src/CMakeFiles/whisper.dir/build
.PHONY : whisper/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/main.cpp.s
.PHONY : main.cpp.s

src/assets.o: src/assets.cpp.o
.PHONY : src/assets.o

# target to build an object file
src/assets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/assets.cpp.o
.PHONY : src/assets.cpp.o

src/assets.i: src/assets.cpp.i
.PHONY : src/assets.i

# target to preprocess a source file
src/assets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/assets.cpp.i
.PHONY : src/assets.cpp.i

src/assets.s: src/assets.cpp.s
.PHONY : src/assets.s

# target to generate assembly for a file
src/assets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/assets.cpp.s
.PHONY : src/assets.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/cursor_backend.o: src/cursor_backend.cpp.o
.PHONY : src/cursor_backend.o

# target to build an object file
src/cursor_backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/cursor_backend.cpp.o
.PHONY : src/cursor_backend.cpp.o

src/cursor_backend.i: src/cursor_backend.cpp.i
.PHONY : src/cursor_backend.i

# target to preprocess a source file
src/cursor_backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/cursor_backend.cpp.i
.PHONY : src/cursor_backend.cpp.i

src/cursor_backend.s: src/cursor_backend.cpp.s
.PHONY : src/cursor_backend.s

# target to generate assembly for a file
src/cursor_backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/cursor_backend.cpp.s
.PHONY : src/cursor_backend.cpp.s

src/gemini_client.o: src/gemini_client.cpp.o
.PHONY : src/gemini_client.o

# target to build an object file
src/gemini_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/gemini_client.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemini_client_test.dir/build.make CMakeFiles/gemini_client_test.dir/src/gemini_client.cpp.o
.PHONY : src/gemini_client.cpp.o

src/gemini_client.i: src/gemini_client.cpp.i
.PHONY : src/gemini_client.i

# target to preprocess a source file
src/gemini_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/gemini_client.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemini_client_test.dir/build.make CMakeFiles/gemini_client_test.dir/src/gemini_client.cpp.i
.PHONY : src/gemini_client.cpp.i

src/gemini_client.s: src/gemini_client.cpp.s
.PHONY : src/gemini_client.s

# target to generate assembly for a file
src/gemini_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/gemini_client.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemini_client_test.dir/build.make CMakeFiles/gemini_client_test.dir/src/gemini_client.cpp.s
.PHONY : src/gemini_client.cpp.s

src/goose.o: src/goose.cpp.o
.PHONY : src/goose.o

# target to build an object file
src/goose.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/goose.cpp.o
.PHONY : src/goose.cpp.o

src/goose.i: src/goose.cpp.i
.PHONY : src/goose.i

# target to preprocess a source file
src/goose.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/goose.cpp.i
.PHONY : src/goose.cpp.i

src/goose.s: src/goose.cpp.s
.PHONY : src/goose.s

# target to generate assembly for a file
src/goose.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/goose.cpp.s
.PHONY : src/goose.cpp.s

src/hyprland.o: src/hyprland.cpp.o
.PHONY : src/hyprland.o

# target to build an object file
src/hyprland.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/hyprland.cpp.o
.PHONY : src/hyprland.cpp.o

src/hyprland.i: src/hyprland.cpp.i
.PHONY : src/hyprland.i

# target to preprocess a source file
src/hyprland.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/hyprland.cpp.i
.PHONY : src/hyprland.cpp.i

src/hyprland.s: src/hyprland.cpp.s
.PHONY : src/hyprland.s

# target to generate assembly for a file
src/hyprland.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/hyprland.cpp.s
.PHONY : src/hyprland.cpp.s

src/tool_manager.o: src/tool_manager.cpp.o
.PHONY : src/tool_manager.o

# target to build an object file
src/tool_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/tool_manager.cpp.o
.PHONY : src/tool_manager.cpp.o

src/tool_manager.i: src/tool_manager.cpp.i
.PHONY : src/tool_manager.i

# target to preprocess a source file
src/tool_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/tool_manager.cpp.i
.PHONY : src/tool_manager.cpp.i

src/tool_manager.s: src/tool_manager.cpp.s
.PHONY : src/tool_manager.s

# target to generate assembly for a file
src/tool_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/tool_manager.cpp.s
.PHONY : src/tool_manager.cpp.s

src/ui.o: src/ui.cpp.o
.PHONY : src/ui.o

# target to build an object file
src/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/ui.cpp.o
.PHONY : src/ui.cpp.o

src/ui.i: src/ui.cpp.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/ui.cpp.i
.PHONY : src/ui.cpp.i

src/ui.s: src/ui.cpp.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/ui.cpp.s
.PHONY : src/ui.cpp.s

src/whisper_manager.o: src/whisper_manager.cpp.o
.PHONY : src/whisper_manager.o

# target to build an object file
src/whisper_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/whisper_manager.cpp.o
.PHONY : src/whisper_manager.cpp.o

src/whisper_manager.i: src/whisper_manager.cpp.i
.PHONY : src/whisper_manager.i

# target to preprocess a source file
src/whisper_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/whisper_manager.cpp.i
.PHONY : src/whisper_manager.cpp.i

src/whisper_manager.s: src/whisper_manager.cpp.s
.PHONY : src/whisper_manager.s

# target to generate assembly for a file
src/whisper_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/whisper_manager.cpp.s
.PHONY : src/whisper_manager.cpp.s

src/wlroots_backend.o: src/wlroots_backend.cpp.o
.PHONY : src/wlroots_backend.o

# target to build an object file
src/wlroots_backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/wlroots_backend.cpp.o
.PHONY : src/wlroots_backend.cpp.o

src/wlroots_backend.i: src/wlroots_backend.cpp.i
.PHONY : src/wlroots_backend.i

# target to preprocess a source file
src/wlroots_backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/wlroots_backend.cpp.i
.PHONY : src/wlroots_backend.cpp.i

src/wlroots_backend.s: src/wlroots_backend.cpp.s
.PHONY : src/wlroots_backend.s

# target to generate assembly for a file
src/wlroots_backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/wlroots_backend.cpp.s
.PHONY : src/wlroots_backend.cpp.s

src/world.o: src/world.cpp.o
.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i
.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s
.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

src/x11_backend.o: src/x11_backend.cpp.o
.PHONY : src/x11_backend.o

# target to build an object file
src/x11_backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/x11_backend.cpp.o
.PHONY : src/x11_backend.cpp.o

src/x11_backend.i: src/x11_backend.cpp.i
.PHONY : src/x11_backend.i

# target to preprocess a source file
src/x11_backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/x11_backend.cpp.i
.PHONY : src/x11_backend.cpp.i

src/x11_backend.s: src/x11_backend.cpp.s
.PHONY : src/x11_backend.s

# target to generate assembly for a file
src/x11_backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/src/x11_backend.cpp.s
.PHONY : src/x11_backend.cpp.s

tests/gemini_client_test.o: tests/gemini_client_test.cpp.o
.PHONY : tests/gemini_client_test.o

# target to build an object file
tests/gemini_client_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemini_client_test.dir/build.make CMakeFiles/gemini_client_test.dir/tests/gemini_client_test.cpp.o
.PHONY : tests/gemini_client_test.cpp.o

tests/gemini_client_test.i: tests/gemini_client_test.cpp.i
.PHONY : tests/gemini_client_test.i

# target to preprocess a source file
tests/gemini_client_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemini_client_test.dir/build.make CMakeFiles/gemini_client_test.dir/tests/gemini_client_test.cpp.i
.PHONY : tests/gemini_client_test.cpp.i

tests/gemini_client_test.s: tests/gemini_client_test.cpp.s
.PHONY : tests/gemini_client_test.s

# target to generate assembly for a file
tests/gemini_client_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemini_client_test.dir/build.make CMakeFiles/gemini_client_test.dir/tests/gemini_client_test.cpp.s
.PHONY : tests/gemini_client_test.cpp.s

wlr-virtual-pointer-unstable-v1-protocol.o: wlr-virtual-pointer-unstable-v1-protocol.c.o
.PHONY : wlr-virtual-pointer-unstable-v1-protocol.o

# target to build an object file
wlr-virtual-pointer-unstable-v1-protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/wlr-virtual-pointer-unstable-v1-protocol.c.o
.PHONY : wlr-virtual-pointer-unstable-v1-protocol.c.o

wlr-virtual-pointer-unstable-v1-protocol.i: wlr-virtual-pointer-unstable-v1-protocol.c.i
.PHONY : wlr-virtual-pointer-unstable-v1-protocol.i

# target to preprocess a source file
wlr-virtual-pointer-unstable-v1-protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/wlr-virtual-pointer-unstable-v1-protocol.c.i
.PHONY : wlr-virtual-pointer-unstable-v1-protocol.c.i

wlr-virtual-pointer-unstable-v1-protocol.s: wlr-virtual-pointer-unstable-v1-protocol.c.s
.PHONY : wlr-virtual-pointer-unstable-v1-protocol.s

# target to generate assembly for a file
wlr-virtual-pointer-unstable-v1-protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CppGoose.dir/build.make CMakeFiles/CppGoose.dir/wlr-virtual-pointer-unstable-v1-protocol.c.s
.PHONY : wlr-virtual-pointer-unstable-v1-protocol.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... CppGoose"
	@echo "... gemini_client_test"
	@echo "... ggml"
	@echo "... ggml-base"
	@echo "... ggml-cpu"
	@echo "... whisper"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/assets.o"
	@echo "... src/assets.i"
	@echo "... src/assets.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/cursor_backend.o"
	@echo "... src/cursor_backend.i"
	@echo "... src/cursor_backend.s"
	@echo "... src/gemini_client.o"
	@echo "... src/gemini_client.i"
	@echo "... src/gemini_client.s"
	@echo "... src/goose.o"
	@echo "... src/goose.i"
	@echo "... src/goose.s"
	@echo "... src/hyprland.o"
	@echo "... src/hyprland.i"
	@echo "... src/hyprland.s"
	@echo "... src/tool_manager.o"
	@echo "... src/tool_manager.i"
	@echo "... src/tool_manager.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... src/whisper_manager.o"
	@echo "... src/whisper_manager.i"
	@echo "... src/whisper_manager.s"
	@echo "... src/wlroots_backend.o"
	@echo "... src/wlroots_backend.i"
	@echo "... src/wlroots_backend.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
	@echo "... src/x11_backend.o"
	@echo "... src/x11_backend.i"
	@echo "... src/x11_backend.s"
	@echo "... tests/gemini_client_test.o"
	@echo "... tests/gemini_client_test.i"
	@echo "... tests/gemini_client_test.s"
	@echo "... wlr-virtual-pointer-unstable-v1-protocol.o"
	@echo "... wlr-virtual-pointer-unstable-v1-protocol.i"
	@echo "... wlr-virtual-pointer-unstable-v1-protocol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P "/home/dill/Downloads/desktop-goose/Desktop Goose v0.31/DesktopGoosev0.31/CMakeFiles/VerifyGlobs.cmake"
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

